# **Alura Challenge TelecomX Parte 2**

## 🛠️ **Preparación de los Datos**

### **Extracción del Archivo Tratado**

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/epjuarez/alura-challenge-telecomx2/refs/heads/main/datos_tratados.csv"

df = pd.read_csv(url)

df.head()

,customerid,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,...,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,account_charges_total,cuentas_diarias
0,0002-orfbo,0,female,0,1,1,9,1,no,dsl,...,no,yes,yes,no,one year,1,mailed check,65.6,593.30,2.186667
1,0003-mknfe,0,male,0,0,0,9,1,yes,dsl,...,no,no,no,yes,month-to-month,0,mailed check,59.9,542.40,1.996667
2,0004-tlhlj,1,male,0,0,0,4,1,no,fiber optic,...,yes,no,no,no,month-to-month,1,electronic check,73.9,280.85,2.463333
3,0011-igkff,1,male,1,1,0,13,1,no,fiber optic,...,yes,no,yes,yes,month-to-month,1,electronic check,98.0,1237.85,3.266667
4,0013-exchz,1,female,1,1,0,3,1,no,fiber optic,...,no,yes,yes,no,month-to-month,1,mailed check,83.9,267.40,2.796667

In [4]:
df.info()
df.shape
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerid                 7043 non-null   object
 1   churn                      7043 non-null   int64
 2   customer_gender            7043 non-null   object
 3   customer_seniorcitizen     7043 non-null   int64
 4   customer_partner           7043 non-null   int64
 5   customer_dependents        7043 non-null   int64
 6   customer_tenure            7043 non-null   int64
 7   phone_phoneservice         7043 non-null   int64
 8   phone_multiplelines        7043 non-null   object
 9   internet_internetservice   7043 non-null   object
 10  internet_onlinesecurity    7043 non-null   object
 11  internet_onlinebackup      7043 non-null   object
 12  internet_deviceprotection  7043 non-null   object
 13  internet_techsupport       7043 non-null   object
 14  internet_streamingtv       7043 non-null   object
 15  internet_streamingmovies   7043 non-null   object
 16  account_contract           7043 non-null   object
 17  account_paperlessbilling   7043 non-null   int64
 18  account_paymentmethod      7043 non-null   object
 19  account_charges_monthly    7043 non-null   float64
 20  account_charges_total      7043 non-null   float64
 21  cuentas_diarias            7043 non-null   float64
dtypes: float64(3), int64(7), object(12)
memory usage: 1.2+ MB

Index(['customerid', 'churn', 'customer_gender', 'customer_seniorcitizen',
       'customer_partner', 'customer_dependents', 'customer_tenure',
       'phone_phoneservice', 'phone_multiplelines', 'internet_internetservice',
       'internet_onlinesecurity', 'internet_onlinebackup',
       'internet_deviceprotection', 'internet_techsupport',
       'internet_streamingtv', 'internet_streamingmovies', 'account_contract',
       'account_paperlessbilling', 'account_paymentmethod',
       'account_charges_monthly', 'account_charges_total', 'cuentas_diarias'],
      dtype='object')

### **Eliminación de Columnas Irrelevantes**

In [6]:
df = df.drop(columns=['customerid'])

In [7]:
df.columns

Index(['churn', 'customer_gender', 'customer_seniorcitizen',
       'customer_partner', 'customer_dependents', 'customer_tenure',
       'phone_phoneservice', 'phone_multiplelines', 'internet_internetservice',
       'internet_onlinesecurity', 'internet_onlinebackup',
       'internet_deviceprotection', 'internet_techsupport',
       'internet_streamingtv', 'internet_streamingmovies', 'account_contract',
       'account_paperlessbilling', 'account_paymentmethod',
       'account_charges_monthly', 'account_charges_total', 'cuentas_diarias'],
      dtype='object')

### **Encoding**

In [8]:
df.dtypes

churn                          int64
customer_gender               object
customer_seniorcitizen         int64
customer_partner               int64
customer_dependents            int64
customer_tenure                int64
phone_phoneservice             int64
phone_multiplelines           object
internet_internetservice      object
internet_onlinesecurity       object
internet_onlinebackup         object
internet_deviceprotection     object
internet_techsupport          object
internet_streamingtv          object
internet_streamingmovies      object
account_contract              object
account_paperlessbilling       int64
account_paymentmethod         object
account_charges_monthly      float64
account_charges_total        float64
cuentas_diarias              float64
dtype: object

In [9]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [10]:
df_encoded.head()

,churn,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,account_paperlessbilling,account_charges_monthly,account_charges_total,cuentas_diarias,...,internet_techsupport_yes,internet_streamingtv_no internet service,internet_streamingtv_yes,internet_streamingmovies_no internet service,internet_streamingmovies_yes,account_contract_one year,account_contract_two year,account_paymentmethod_credit card (automatic),account_paymentmethod_electronic check,account_paymentmethod_mailed check
0,0,0,1,1,9,1,1,65.6,593.30,2.186667,...,True,False,True,False,False,True,False,False,False,True
1,0,0,0,0,9,1,0,59.9,542.40,1.996667,...,False,False,False,False,True,False,False,False,False,True
2,1,0,0,0,4,1,1,73.9,280.85,2.463333,...,False,False,False,False,False,False,False,False,True,False
3,1,1,1,0,13,1,1,98.0,1237.85,3.266667,...,False,False,True,False,True,False,False,False,True,False
4,1,1,1,0,3,1,1,83.9,267.40,2.796667,...,True,False,True,False,False,False,False,False,False,True

In [11]:
df_encoded.dtypes.value_counts()

bool       22
int64       7
float64     3
Name: count, dtype: int64

### **Verificación de la Proporción de Cancelación (Churn)**

In [13]:
churn_count = df_encoded['churn'].value_counts()

churn_ratio = df_encoded['churn'].value_counts(normalize=True) * 100

print("Conteo de clientes por clase:")
print(churn_count)

print("\nProporción (%):")
print(churn_ratio)

Conteo de clientes por clase:
churn
0    5174
1    1869
Name: count, dtype: int64

Proporción (%):
churn
0    73.463013
1    26.536987
Name: proportion, dtype: float64